### ISSUE TITLE
怎么去掉那个回音呢? 总是会有回音

### ISSUE THREAD

**Issue by keepJion** [wintelsui/CallKitDemo#2]

**Comment by wintelsui** [comment]
如果说是Demo里,接听后的Mic声音的话,就是void stopAudio(){

CallAudio *audio = [ CallAudio sharedCallAudio ];

[audio stopAudio ];

}




void startAudio(){

CallAudio *audio = [ CallAudio sharedCallAudio ];

[audio startAudio ];

}




void configureAudioSession(){

CallAudio *audio = [ CallAudio sharedCallAudio ];

[audio configureAudioSession ];

}

这些代码,会开启麦克风


Sent using wintelsui's CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.8.28&pv=9.3&source=email_footer_2]
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.1.19&pv=10.11.6&source=email_footer_2]

**Comment by keepJion** [comment]
我是放到了我的项目中的,网络语音通话  我是要在
- (void)provider:(CXProvider *)provider performAnswerCallAction:(CXAnswerCallAction *)action{
    WTCall *call = [_callManager callWithUUID:action.callUUID];
    if (call == nil) {
        [action fail];
    }else{
        configureAudioSession();
        [call answerWTCallCall];
        [action fulfill];
    }
}
这个方法里面去掉么?

**Comment by wintelsui** [comment]
只需要把ProviderDelegate里面的#pragma mark - CallAudio

void stopAudio(){

CallAudio *audio = [ CallAudio sharedCallAudio ];

[audio stopAudio ];

}




void startAudio(){

CallAudio *audio = [ CallAudio sharedCallAudio ];

[audio startAudio ];

}




void configureAudioSession(){

CallAudio *audio = [ CallAudio sharedCallAudio ];

[audio configureAudioSession ];

}

把这三个方法里面这几行注释掉就行,这几行代码连接着 CallAudio这个类,CallAudio实现的那个声音 Sent using wintelsui's CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.8.28&pv=9.3&source=email_footer_2]
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.1.19&pv=10.11.6&source=email_footer_2]
On 周五, 10月 14, 2016 at 4:36 下午, keepJion <notifications@github.com> wrote:
我是放到了我的项目中的,网络语音通话 我是要在

 * (void)provider:(CXProvider *)provider performAnswerCallAction:(CXAnswerCallAction *)action{ WTCall *call = [_callManager callWithUUID:action.callUUID]; if (call == nil) { [action fail]; }else{ configureAudioSession(); [call answerWTCallCall]; [action fulfill]; } } 这个方法里面去掉么?

**Comment by keepJion** [comment]
真是太感谢你了!!!!赞

**Comment by keepJion** [comment]
那三个方法全部注释了,但是现在就是第一次没有声音,要第二次才会有声音了!

**Comment by wintelsui** [comment]
我这儿项目有时候刚编译完，点击接听，voip前几次也没声音，之后就都可以了………，也不知道原因，有时候应用刚开后，进后台，第一次进来的呼叫呼叫，屏幕刚亮就挂断了，也不知道原因中……

Sent using wintelsui's CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.8.28&pv=9.3&source=email_footer_2]
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.1.21&pv=10.0.2&source=email_footer_2]
On 周六, 10月 15, 2016 at 3:51 下午, keepJion <notifications@github.com> wrote:
那三个方法全部注释了,但是现在就是第一次没有声音,要第二次才会有声音了!
